Boilerplate
hphd-labs/roomie-webapp pull request #10
Opened 2017-09-24 16:01 UTC by tratnayake

The tree is fixed (?)

Made the changes referenced in the old PR.

2017-09-24 19:13 UTC, AndrewBurian requested changes
Tests fail
```
hphd-labs/roomie-webapp/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: hphd-labs/roomie-webapp/test/test_helper.js: Unexpected token (21:4)
  19 | function renderComponent(ComponentClass, props = {}, state = {}) {
  20 |   const componentInstance =  TestUtils.renderIntoDocument(
> 21 |     <Provider store={createStore(reducers, state)}>
     |     ^
  22 |       <ComponentClass {...props} />
  23 |     </Provider>
  24 |   );
```

2017-09-24 19:13 UTC, AndrewBurian commented on src/components/splash_index.js
> +        <img className="center-block" src="./room.png"></img>
Another static asset for `/dist` maybe?

2017-09-24 19:14 UTC, AndrewBurian requested changes

2017-09-24 19:14 UTC, AndrewBurian commented on README.md
> -# roomie-webapp
Readme got nuked again

2017-09-24 20:18 UTC, AndrewBurian approved these changes

2017-09-25 17:45 UTC, gdabu approved these changes

2017-09-26 01:20 UTC, merged